# Generated by Django 4.0.4 on 2022-05-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatnova_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatnova_api.post'),
        ),
    ]
